apiVersion: apps/v1
kind: Deployment
metadata:
  name: sans-webapp
spec:
  selector:
    matchLabels:
      app: sans-webapp
  template:
    metadata:
      labels:
        app: sans-webapp
    spec:
      containers:
        - name: sans-webapp-image
          image: ghcr.io/mhughdo/3s-webapp:GITHUB_SHA
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: '256Mi'
              cpu: '250m'
            limits:
              memory: '2Gi'
              cpu: "2500m"
# ---
# apiVersion: extensions/v1beta1
# kind: Ingress
# metadata:
#   name: 3s-webapp-ingress
#   annotations:
#     kubernetes.io/ingress.class: nginx
#     cert-manager.io/cluster-issuer: letsencrypt-prod
#     nginx.ingress.kubernetes.io/rewrite-target: /
# spec:
#   tls:
#     - hosts:
#         - awm.hughdo.dev
#         - www.awm.hughdo.dev
#       secretName: 3s-webapp-tls
#   rules:
#     - host: awm.hughdo.dev
#       http:
#         paths:
#           - path: /
#             backend:
#               serviceName: 3s-webapp-svc
#               servicePort: 80
