apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
namespace: default
images:
- name: ghcr.io/mhughdo/3s-webapp
  newName: ghcr.io/mhughdo/3s-webapp
  newTag: fix-kustomization-6ee22b86f54fb1cac87e91d9ae5b9052d5552b8f
