apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
- ingress-route.yml
namespace: default
images:
- name: ghcr.io/mhughdo/3s-webapp
  newName: ghcr.io/mhughdo/3s-webapp
  newTag: ssl-tls-traefik-24a8b23dd45b212864ecae5b8f627fdf2b4cc0d4
