apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
- ingress-route.yml
namespace: default
images:
- name: ghcr.io/mhughdo/3s-webapp
  newName: ghcr.io/mhughdo/3s-webapp
  newTag: master-49a4088ee31d0f76f247e0994f5f9c67d2077433
