apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
- ingress-route.yml
namespace: default
images:
- name: ghcr.io/mhughdo/3s-webapp
  newName: ghcr.io/mhughdo/3s-webapp
  newTag: fix-kustomization-files-type-888af245a9df1758b5ecaaa626cff4c195e63b39
